version: '3'

services:
  app:
    image: "astldocker/synology-nas-monitoring"
    ports:
      - "3003:3003"
      - "3004:8888"
      - "8086:8086"
      - "22022:22"
      - "8125:8125/udp"
    environment:
      - "TZ=America/New_York"
      - "PGID=100"
      - "PUID=1027"
    volumes:
      - /volume1/docker/influxdb:/var/lib/influxdb
      - /volume1/docker/grafana:/var/lib/grafana
      - /volume1/docker/backup:/var/backups
